### ISSUE TITLE
TooManyOrigins crashes if you open its settings

### ISSUE THREAD

**Issue by GGSkyOne** [MerchantPug/toomanyorigins#64]
If you open TooManyOrigins settings with ModMenu game crashes. 
[crash-2023-06-28_12.29.46-client.txt](https://github.com/MerchantPug/toomanyorigins/files/11892578/crash-2023-06-28_12.29.46-client.txt)

Edited: Minecraft 1.20.1, TooManyOrigins v0.9.1+1.20.1

**Comment by ChrysanthCow** [comment]
I think that this is a bug to do with hiding my mod from mod menu integration with MidnightLib.

I also found this and I think that this is an issue on their end, but I'd need to investigate a bit more.

Although it's something that I don't really want to do because I'm planning on making my own config system later down the line.

**Comment by ChrysanthCow** [comment]
I don't think I updated MidnightLib to a 1.20 version on my end. I'll probably push another patch at a later date.

Just avoid opening the config menu for now, there's literally nothing there.

**Comment by ChrysanthCow** [comment]
I've tested it with an updated MidnightLib, there's no crash but ModMenu does output an error with the config.

I'll make a bug report over to MidnightLib's repo when I can

**Comment by GGSkyOne** [comment]
Okay, thank you for the answer

**Comment by ChrysanthCow** [comment]
There was something that I could do, and that's fix my config.

This should be fixed in beta 14 but I'll leave this open until it's fixed on the main branch.
